In [1]:
%load_ext autoreload
%autoreload 2

from basket_analysis import (
    read_basket, read_id_and_cluster, cluster_association_rules)

In [2]:
basket_dataset = read_basket()

In [3]:
basket_dataset

,invoice_id,list_of_goods,customer_id
0,5062209,"['megaman zero 3', 'energy bar', 'pokemon viol...",4925
1,4272512,"['black beer', 'bramble', 'laptop', 'pokemon v...",19046
2,7121052,"['soup', 'shallot', 'cake', 'fresh bread', 'cr...",10318
3,5847748,"['soup', 'cooking oil', 'cereals', 'oil', 'dog...",27283
4,6336114,"['eggplant', 'mint green tea', 'oil', 'bacon',...",16072
...,...,...,...
99995,5389466,"['frozen smoothie', 'avocado', 'dog food', 'ch...",26170
99996,10387390,"['cake', 'antioxydant juice', 'honey', 'toothp...",19691
99997,7103407,"['candy bars', 'spaghetti', 'oil', 'final fant...",1720
99998,4093515,"['shallot', 'cereals', 'oil', 'deodorant', 'me...",24989
99999,6611217,"['soup', 'napkins', 'pokemon violet', 'ratchet...",482

In [4]:
id_and_cluster = read_id_and_cluster()

In [5]:
merged_df = basket_dataset.merge(id_and_cluster, on='customer_id', how="left")
merged_df = merged_df.drop(columns=['invoice_id'])

In [6]:
cluster_groups = {cluster: df for cluster, df in merged_df.groupby('Cluster')}

# Vegetarians

In [7]:
vegetarian_df = cluster_groups['Vegetarian']
cluster_association_rules(vegetarian_df)

We have 10984 rows in the train set.
We have 2746 rows in the test set.

 Frequent Itemsets (support >= 0.5)

      support                                   itemsets
31   0.768664                                 (tomatoes)
0    0.643572                                (asparagus)
5    0.546522                                  (carrots)
55   0.527586                      (tomatoes, asparagus)
76   0.452385                        (tomatoes, carrots)
..        ...                                        ...
82   0.051074                        (tomatoes, chicken)
163  0.050801  (tomatoes, asparagus, carrots, flax seed)
59   0.050346                   (mashed potato, avocado)
120  0.050346           (asparagus, toothpaste, carrots)
11   0.050164                                 (escalope)

[173 rows x 2 columns]

 Association rules (confidence >= 0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(avocado),(asparagus),0.143299,0.643572,0.099964,0.697586,1.083927,1.0,0.007740,1.178607,0.090380,0.145527,0.151541,0.426456
1,(asparagus),(carrots),0.643572,0.546522,0.381464,0.592729,1.084547,1.0,0.029737,1.113454,0.218714,0.471741,0.101894,0.645357
2,(carrots),(asparagus),0.546522,0.643572,0.381464,0.697984,1.084547,1.0,0.029737,1.180162,0.171906,0.471741,0.152659,0.645357
3,(cauliflower),(asparagus),0.197196,0.643572,0.141387,0.716990,1.114078,1.0,0.014478,1.259416,0.127549,0.202161,0.205981,0.468341
4,(asparagus),(cauliflower),0.643572,0.197196,0.141387,0.219692,1.114078,1.0,0.014478,1.028829,0.287286,0.202161,0.028021,0.468341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,"(tomatoes, melons)","(mashed potato, carrots)",0.212309,0.204388,0.051438,0.242281,1.185398,1.0,0.008045,1.050009,0.198557,0.140828,0.047628,0.246976
390,"(mashed potato, carrots)","(tomatoes, melons)",0.204388,0.212309,0.051438,0.251670,1.185398,1.0,0.008045,1.052599,0.196580,0.140828,0.049971,0.246976
391,"(mashed potato, melons)","(tomatoes, carrots)",0.095685,0.452385,0.051438,0.537583,1.188331,1.0,0.008152,1.184245,0.175252,0.103575,0.155580,0.325644
392,"(carrots, melons)","(tomatoes, mashed potato)",0.153951,0.281500,0.051438,0.334122,1.186932,1.0,0.008101,1.079026,0.186150,0.133950,0.073238,0.258426
393,(melons),"(tomatoes, mashed potato, carrots)",0.256009,0.175710,0.051438,0.200925,1.143500,1.0,0.006455,1.031555,0.168674,0.135265,0.030589,0.246835

 Top 10 rules by lift (support >= 0.02)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1805,"(cauliflower, tomatoes, frozen vegetables)","(asparagus, carrots)",0.040878,0.381464,0.022123,0.541203,1.418752,1.0,0.006530,1.348168,0.307735,0.055278,0.258253,0.299599
1804,"(asparagus, frozen vegetables, carrots)","(cauliflower, tomatoes)",0.097050,0.163328,0.022123,0.227955,1.395684,1.0,0.006272,1.083708,0.313977,0.092854,0.077242,0.181703
1522,"(shallot, asparagus)","(tomatoes, frozen vegetables)",0.093318,0.182811,0.023762,0.254634,1.392879,1.0,0.006702,1.096359,0.311093,0.094156,0.087890,0.192307
1809,"(cauliflower, frozen vegetables)","(tomatoes, asparagus, carrots)",0.048707,0.327294,0.022123,0.454206,1.387759,1.0,0.006181,1.232526,0.293720,0.062516,0.188658,0.260900
1919,"(shallot, asparagus)","(tomatoes, mashed potato, carrots)",0.093318,0.175710,0.022669,0.242927,1.382543,1.0,0.006272,1.088785,0.305173,0.092018,0.081545,0.185971
1807,"(cauliflower, tomatoes, carrots)","(asparagus, frozen vegetables)",0.102877,0.155590,0.022123,0.215044,1.382122,1.0,0.006116,1.075742,0.308179,0.093606,0.070409,0.178616
1931,"(zucchini, mashed potato)","(tomatoes, asparagus, carrots)",0.059086,0.327294,0.026675,0.451464,1.379382,1.0,0.007337,1.226365,0.292309,0.074158,0.184582,0.266483
1547,"(tomatoes, green grapes)","(asparagus, mashed potato)",0.074290,0.236435,0.024126,0.324755,1.373549,1.0,0.006561,1.130797,0.293784,0.084180,0.115668,0.213398
1915,"(shallot, tomatoes, asparagus)","(mashed potato, carrots)",0.080845,0.204388,0.022669,0.280405,1.371926,1.0,0.006146,1.105639,0.294942,0.086338,0.095546,0.195659
1917,"(shallot, carrots)","(tomatoes, asparagus, mashed potato)",0.081937,0.202749,0.022669,0.276667,1.364574,1.0,0.006057,1.102190,0.291016,0.086518,0.092715,0.194238

 Test set: top 10 rules by lift (support >= 0.05)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
368,"(asparagus, green beans)","(tomatoes, mashed potato)",0.139111,0.288784,0.053168,0.382199,1.323478,1.0,0.012995,1.151206,0.283910,0.141885,0.131346,0.283155
364,"(tomatoes, asparagus, mashed potato)",(green beans),0.209760,0.191916,0.053168,0.253472,1.320749,1.0,0.012912,1.082457,0.307316,0.152560,0.076176,0.265256
371,(green beans),"(tomatoes, asparagus, mashed potato)",0.191916,0.209760,0.053168,0.277040,1.320749,1.0,0.012912,1.093062,0.300530,0.152560,0.085139,0.265256
298,"(asparagus, flax seed)","(tomatoes, carrots)",0.088128,0.433722,0.050255,0.570248,1.314778,1.0,0.012032,1.317686,0.262554,0.106564,0.241094,0.343058
367,"(tomatoes, green beans)","(asparagus, mashed potato)",0.159869,0.253095,0.053168,0.332574,1.314026,1.0,0.012706,1.119082,0.284456,0.147773,0.106411,0.271323
369,"(asparagus, mashed potato)","(tomatoes, green beans)",0.253095,0.159869,0.053168,0.210072,1.314026,1.0,0.012706,1.063554,0.319961,0.147773,0.059756,0.271323
370,"(green beans, mashed potato)","(tomatoes, asparagus)",0.077203,0.524763,0.053168,0.688679,1.312362,1.0,0.012655,1.526518,0.257928,0.096881,0.344914,0.394999
344,"(shallot, asparagus)","(tomatoes, carrots)",0.090313,0.433722,0.050983,0.564516,1.301563,1.0,0.011812,1.300343,0.254695,0.107775,0.230972,0.341032
291,"(cauliflower, asparagus)","(tomatoes, carrots)",0.132921,0.433722,0.075018,0.564384,1.301257,1.0,0.017368,1.299947,0.267003,0.152593,0.230738,0.368674
290,"(cauliflower, tomatoes)","(asparagus, carrots)",0.151493,0.383103,0.075018,0.495192,1.292584,1.0,0.016981,1.222044,0.266769,0.163233,0.181699,0.345505

Mean Relative Lift Difference: 0.032964609689144074

# Wellness Urbanites

In [8]:
wellness_df = cluster_groups['Wellness Urbanites']
cluster_association_rules(wellness_df)

We have 10030 rows in the train set.
We have 2508 rows in the test set.

 Frequent Itemsets (support >= 0.5)

      support                                    itemsets
7    0.752343                                 (champagne)
13   0.539681                                (fresh tuna)
69   0.445464                     (fresh tuna, champagne)
5    0.428215                      (bluetooth headphones)
54   0.354437           (bluetooth headphones, champagne)
..        ...                                         ...
72   0.050947                (champagne, gluten free bar)
26   0.050349                                       (oil)
59   0.050349       (grated cheese, bluetooth headphones)
86   0.050150                (sparkling water, champagne)
133  0.050050  (salmon, fresh tuna, bluetooth headphones)

[161 rows x 2 columns]

 Association rules (confidence >= 0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(almonds),(bluetooth headphones),0.119940,0.428215,0.058425,0.487116,1.137548,1.0,0.007064,1.114841,0.137396,0.119300,0.103011,0.311777
1,(almonds),(champagne),0.119940,0.752343,0.097507,0.812968,1.080581,1.0,0.007271,1.324140,0.084735,0.125853,0.244793,0.471286
2,(almonds),(fresh tuna),0.119940,0.539681,0.071286,0.594347,1.101294,1.0,0.006557,1.134762,0.104513,0.121166,0.118758,0.363218
3,(asparagus),(champagne),0.100299,0.752343,0.079960,0.797217,1.059645,1.0,0.004501,1.221289,0.062563,0.103484,0.181193,0.451749
4,(asparagus),(fresh tuna),0.100299,0.539681,0.054835,0.546720,1.013042,1.0,0.000706,1.015528,0.014310,0.093713,0.015291,0.324163
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,"(frozen smoothie, spaghetti)","(fresh tuna, champagne)",0.110469,0.445464,0.065005,0.588448,1.320978,1.0,0.015795,1.347426,0.273161,0.132413,0.257844,0.367187
347,"(frozen smoothie, champagne)","(fresh tuna, spaghetti)",0.237886,0.204487,0.065005,0.273261,1.336326,1.0,0.016360,1.094634,0.330239,0.172259,0.086453,0.295577
348,"(fresh tuna, spaghetti)","(frozen smoothie, champagne)",0.204487,0.237886,0.065005,0.317894,1.336326,1.0,0.016360,1.117295,0.316374,0.172259,0.104981,0.295577
349,"(spaghetti, champagne)","(frozen smoothie, fresh tuna)",0.276072,0.176969,0.065005,0.235464,1.330538,1.0,0.016149,1.076510,0.343161,0.167523,0.071073,0.301394
350,(frozen smoothie),"(fresh tuna, spaghetti, champagne)",0.283948,0.175573,0.065005,0.228933,1.303915,1.0,0.015151,1.069202,0.325505,0.164771,0.064723,0.299588

 Top 10 rules by lift (support >= 0.02)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1201,"(cottage cheese, spaghetti)","(avocado, champagne)",0.080857,0.205882,0.024227,0.299630,1.455346,1.0,0.007580,1.133855,0.340402,0.092290,0.118053,0.208653
1493,"(salmon, champagne)","(bluetooth headphones, spaghetti)",0.129312,0.162114,0.030508,0.235929,1.455331,1.0,0.009545,1.096608,0.359338,0.116928,0.088097,0.212060
1576,"(cottage cheese, spaghetti)","(frozen smoothie, champagne)",0.080857,0.237886,0.027916,0.345253,1.451335,1.0,0.008681,1.163982,0.338336,0.095989,0.140880,0.231302
1771,"(frozen smoothie, bluetooth headphones)","(fresh tuna, spaghetti, champagne)",0.137488,0.175573,0.034995,0.254532,1.449721,1.0,0.010856,1.105919,0.359661,0.125852,0.095774,0.226925
1686,"(cottage cheese, spaghetti)","(frozen smoothie, fresh tuna)",0.080857,0.176969,0.020538,0.254007,1.435321,1.0,0.006229,1.103270,0.329972,0.086555,0.093603,0.185032
1195,"(frozen smoothie, avocado)","(cottage cheese, champagne)",0.082851,0.180359,0.021436,0.258724,1.434498,1.0,0.006493,1.105717,0.330254,0.088660,0.095610,0.188787
1763,"(frozen smoothie, fresh tuna, bluetooth headph...","(spaghetti, champagne)",0.088734,0.276072,0.034995,0.394382,1.428549,1.0,0.010498,1.195355,0.329200,0.106106,0.163428,0.260571
1769,"(frozen smoothie, spaghetti)","(fresh tuna, bluetooth headphones, champagne)",0.110469,0.222333,0.034995,0.316787,1.424831,1.0,0.010434,1.138250,0.335191,0.117509,0.121458,0.237093
1762,"(bluetooth headphones, fresh tuna, spaghetti)","(frozen smoothie, champagne)",0.103290,0.237886,0.034995,0.338803,1.424223,1.0,0.010424,1.152627,0.332173,0.114295,0.132417,0.242956
1768,"(frozen smoothie, bluetooth headphones, champa...","(fresh tuna, spaghetti)",0.120339,0.204487,0.034995,0.290804,1.422116,1.0,0.010387,1.121711,0.337428,0.120743,0.108505,0.230970

 Test set: top 10 rules by lift (support >= 0.05)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
354,"(champagne, laptop)","(fresh tuna, bluetooth headphones)",0.157097,0.267145,0.059410,0.378173,1.415607,1.0,0.017442,1.178550,0.348308,0.162842,0.151500,0.300280
351,"(fresh tuna, bluetooth headphones)","(champagne, laptop)",0.267145,0.157097,0.059410,0.222388,1.415607,1.0,0.017442,1.083963,0.400611,0.162842,0.077459,0.300280
332,"(fresh tuna, cottage cheese)","(bluetooth headphones, champagne)",0.137959,0.353270,0.068581,0.497110,1.407169,1.0,0.019844,1.286027,0.335660,0.162264,0.222411,0.345620
334,"(cottage cheese, bluetooth headphones)","(fresh tuna, champagne)",0.111643,0.453349,0.068581,0.614286,1.354994,1.0,0.017967,1.417243,0.294915,0.138153,0.294405,0.382781
352,"(fresh tuna, laptop)","(bluetooth headphones, champagne)",0.124402,0.353270,0.059410,0.477564,1.351841,1.0,0.015462,1.237914,0.297246,0.142040,0.192189,0.322868
335,"(cottage cheese, champagne)","(fresh tuna, bluetooth headphones)",0.190989,0.267145,0.068581,0.359081,1.344144,1.0,0.017559,1.143445,0.316475,0.176049,0.125450,0.307899
333,"(fresh tuna, bluetooth headphones)","(cottage cheese, champagne)",0.267145,0.190989,0.068581,0.256716,1.344144,1.0,0.017559,1.088429,0.349362,0.176049,0.081244,0.307899
355,(laptop),"(fresh tuna, bluetooth headphones, champagne)",0.191388,0.231260,0.059410,0.310417,1.342284,1.0,0.015150,1.114789,0.315357,0.163557,0.102969,0.283657
347,"(fresh tuna, bluetooth headphones, champagne)",(laptop),0.231260,0.191388,0.059410,0.256897,1.342284,1.0,0.015150,1.088156,0.331713,0.163557,0.081014,0.283657
374,"(cottage cheese, spaghetti)","(fresh tuna, champagne)",0.088517,0.453349,0.053828,0.608108,1.341368,1.0,0.013699,1.394902,0.279207,0.110294,0.283104,0.363421

Mean Relative Lift Difference: 0.04024897038029101

# Student

In [9]:
student_df = cluster_groups['Student']
cluster_association_rules(student_df)

We have 21272 rows in the train set.
We have 5319 rows in the test set.

 Frequent Itemsets (support >= 0.5)

      support                            itemsets
27   0.725414                               (oil)
12   0.516124                       (cooking oil)
76   0.411668                  (cooking oil, oil)
5    0.395402                              (cake)
35   0.348345                               (tea)
..        ...                                 ...
117  0.050630           (cake, french fries, oil)
124  0.050395  (candy bars, cooking oil, napkins)
148  0.050348        (cake, candy bars, tea, oil)
104  0.050160             (whole wheat rice, oil)
73   0.050066                 (cooking oil, milk)

[153 rows x 2 columns]

 Association rules (confidence >= 0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(asparagus),(cake),0.131299,0.395402,0.057728,0.439671,1.111957,1.0,0.005812,1.079004,0.115903,0.123095,0.073219,0.292835
1,(asparagus),(cooking oil),0.131299,0.516124,0.073806,0.562120,1.089116,1.0,0.006039,1.105040,0.094192,0.128667,0.095056,0.352560
2,(asparagus),(oil),0.131299,0.725414,0.103845,0.790906,1.090282,1.0,0.008599,1.313218,0.095322,0.137933,0.238512,0.467030
3,(babies food),(oil),0.092516,0.725414,0.067789,0.732724,1.010077,1.0,0.000676,1.027350,0.010993,0.090368,0.026621,0.413086
4,(candy bars),(cake),0.312476,0.395402,0.139808,0.447420,1.131556,1.0,0.016254,1.094136,0.169101,0.246111,0.086037,0.400502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,"(gums, tea)","(cooking oil, oil)",0.103939,0.411668,0.053827,0.517865,1.257968,1.0,0.011038,1.220265,0.228854,0.116563,0.180506,0.324309
305,"(gums, cooking oil)","(oil, tea)",0.115927,0.278159,0.053827,0.464315,1.669241,1.0,0.021580,1.347509,0.453498,0.158193,0.257890,0.328912
306,"(gums, oil)","(cooking oil, tea)",0.160587,0.198712,0.053827,0.335187,1.686800,1.0,0.021916,1.205284,0.485055,0.176208,0.170320,0.303033
307,"(cooking oil, tea)","(gums, oil)",0.198712,0.160587,0.053827,0.270878,1.686800,1.0,0.021916,1.151265,0.508134,0.176208,0.131391,0.303033
308,(gums),"(oil, cooking oil, tea)",0.201862,0.164912,0.053827,0.266651,1.616934,1.0,0.020537,1.138733,0.478044,0.171999,0.121831,0.296524

 Top 10 rules by lift (support >= 0.02)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
124,(white wine),(cider),0.061583,0.051429,0.021390,0.347328,6.753534,1.0,0.018222,1.453366,0.907837,0.233453,0.311942,0.381617
125,(cider),(white wine),0.051429,0.061583,0.021390,0.415905,6.753534,1.0,0.018222,1.606616,0.898119,0.233453,0.377574,0.381617
23,(white wine),(beer),0.061583,0.051006,0.020214,0.328244,6.435403,1.0,0.017073,1.412707,0.900037,0.218830,0.292139,0.362279
22,(beer),(white wine),0.051006,0.061583,0.020214,0.396313,6.435403,1.0,0.017073,1.554477,0.890005,0.218830,0.356697,0.362279
9,(tomatoes),(asparagus),0.085088,0.131299,0.023035,0.270718,2.061840,1.0,0.011863,1.191173,0.562892,0.119134,0.160491,0.223078
4,(carrots),(asparagus),0.076862,0.131299,0.020449,0.266055,2.026324,1.0,0.010358,1.183605,0.548667,0.108941,0.155123,0.210901
1592,"(muffins, cake)","(oil, cooking oil, tea)",0.075216,0.164912,0.023129,0.307500,1.864635,1.0,0.010725,1.205904,0.501417,0.106586,0.170746,0.223875
1591,"(cake, cooking oil, tea)","(muffins, oil)",0.092187,0.134778,0.023129,0.250892,1.861522,1.0,0.010704,1.155003,0.509802,0.113469,0.134202,0.211250
1587,"(muffins, cake, oil)","(cooking oil, tea)",0.063558,0.198712,0.023129,0.363905,1.831321,1.0,0.010499,1.259699,0.484756,0.096717,0.206160,0.240150
1577,"(gums, cake)","(oil, cooking oil, tea)",0.089507,0.164912,0.027031,0.301996,1.831258,1.0,0.012270,1.196394,0.498551,0.118875,0.164155,0.232953

 Test set: top 10 rules by lift (support >= 0.05)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
198,"(gums, cooking oil)",(tea),0.104155,0.348938,0.058658,0.563177,1.613975,1.0,0.022314,1.490448,0.424640,0.148713,0.329061,0.365640
208,"(muffins, cooking oil)",(tea),0.092311,0.348938,0.050761,0.549898,1.575920,1.0,0.018551,1.446478,0.402616,0.129995,0.308665,0.347686
242,(tea),"(muffins, oil)",0.348938,0.135364,0.072758,0.208513,1.540389,1.0,0.025524,1.092420,0.538832,0.176793,0.084601,0.373006
239,"(muffins, oil)",(tea),0.135364,0.348938,0.072758,0.537500,1.540389,1.0,0.025524,1.407702,0.405735,0.176793,0.289622,0.373006
241,(muffins),"(oil, tea)",0.168829,0.281632,0.072758,0.430958,1.530216,1.0,0.025210,1.262416,0.416879,0.192633,0.207868,0.344651
240,"(oil, tea)",(muffins),0.281632,0.168829,0.072758,0.258344,1.530216,1.0,0.025210,1.120697,0.482340,0.192633,0.107698,0.344651
234,"(gums, oil)",(tea),0.154164,0.348938,0.082158,0.532927,1.527283,1.0,0.028365,1.393919,0.408167,0.195176,0.282598,0.384190
237,(tea),"(gums, oil)",0.348938,0.154164,0.082158,0.235453,1.527283,1.0,0.028365,1.106322,0.530276,0.195176,0.096104,0.384190
201,(gums),"(cooking oil, tea)",0.192517,0.200226,0.058658,0.304688,1.521721,1.0,0.020111,1.150237,0.424590,0.175577,0.130614,0.298823
200,"(cooking oil, tea)",(gums),0.200226,0.192517,0.058658,0.292958,1.521721,1.0,0.020111,1.142057,0.428683,0.175577,0.124387,0.298823

Mean Relative Lift Difference: 0.02799910951866848

# Extended Household

In [10]:
extended_household_df = cluster_groups['Extended Household']
cluster_association_rules(extended_household_df)

We have 11944 rows in the train set.
We have 2986 rows in the test set.

 Frequent Itemsets (support >= 0.5)

      support                                  itemsets
1    0.786587                             (babies food)
26   0.558272                         (ratchet & clank)
59   0.464082            (ratchet & clank, babies food)
15   0.429588                               (minecraft)
50   0.359595                  (babies food, minecraft)
..        ...                                       ...
125  0.050569          (babies food, cooking oil, milk)
158  0.050569  (ratchet & clank, cooking oil, escalope)
103  0.050318                       (minecraft, turkey)
38   0.050151                  (babies food, asparagus)
79   0.050151             (cooking oil, pokemon shield)

[176 rows x 2 columns]

 Association rules (confidence >= 0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(asparagus),(babies food),0.063212,0.786587,0.050151,0.793377,1.008632,1.0,0.000429,1.032862,0.009136,0.062716,0.031817,0.428567
1,(bacon),(babies food),0.083557,0.786587,0.070244,0.840681,1.068770,1.0,0.004520,1.339533,0.070212,0.087817,0.253471,0.464992
2,(body spray),(babies food),0.073593,0.786587,0.062374,0.847554,1.077508,1.0,0.004487,1.399923,0.077647,0.078182,0.285675,0.463426
3,(babies food),(burgers),0.786587,0.225301,0.188714,0.239915,1.064862,1.0,0.011495,1.019226,0.285414,0.229251,0.018863,0.538761
4,(burgers),(babies food),0.225301,0.786587,0.188714,0.837607,1.064862,1.0,0.011495,1.314172,0.078625,0.229251,0.239065,0.538761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,"(ratchet & clank, ratchet & clank 2)","(babies food, minecraft)",0.155727,0.359595,0.067398,0.432796,1.203565,1.0,0.011399,1.129056,0.200332,0.150467,0.114304,0.310111
385,"(ratchet & clank, minecraft)","(babies food, ratchet & clank 2)",0.257870,0.216343,0.067398,0.261364,1.208099,1.0,0.011609,1.060951,0.232106,0.165672,0.057449,0.286448
386,"(babies food, ratchet & clank 2)","(ratchet & clank, minecraft)",0.216343,0.257870,0.067398,0.311533,1.208099,1.0,0.011609,1.077945,0.219807,0.165672,0.072309,0.286448
387,"(minecraft, ratchet & clank 2)","(ratchet & clank, babies food)",0.119893,0.464082,0.067398,0.562151,1.211317,1.0,0.011758,1.223978,0.198217,0.130470,0.182992,0.353690
388,(ratchet & clank 2),"(ratchet & clank, babies food, minecraft)",0.256363,0.223292,0.067398,0.262900,1.177382,1.0,0.010154,1.053735,0.202596,0.163485,0.050995,0.282369

 Top 10 rules by lift (support >= 0.02)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1909,"(minecraft, ratchet & clank 2, babies food)","(pet food, ratchet & clank)",0.104069,0.177328,0.025620,0.246179,1.388271,1.0,0.007165,1.091336,0.312166,0.100164,0.083692,0.195327
1913,"(minecraft, ratchet & clank 2)","(pet food, ratchet & clank, babies food)",0.119893,0.155224,0.025620,0.213687,1.376634,1.0,0.007009,1.074351,0.310860,0.102685,0.069205,0.189368
1907,"(pet food, ratchet & clank, ratchet & clank 2)","(minecraft, babies food)",0.051993,0.359595,0.025620,0.492754,1.370303,1.0,0.006923,1.262513,0.285055,0.066377,0.207929,0.282000
1911,"(pet food, ratchet & clank, minecraft)","(babies food, ratchet & clank 2)",0.086654,0.216343,0.025620,0.295652,1.366590,1.0,0.006872,1.112600,0.293702,0.092363,0.101204,0.207037
1912,"(pet food, minecraft, babies food)","(ratchet & clank, ratchet & clank 2)",0.120479,0.155727,0.025620,0.212648,1.365518,1.0,0.006858,1.072294,0.304344,0.102239,0.067420,0.188582
1914,"(pet food, ratchet & clank 2)","(ratchet & clank, babies food, minecraft)",0.084059,0.223292,0.025620,0.304781,1.364943,1.0,0.006850,1.117213,0.291906,0.090936,0.104916,0.209758
1685,"(babies food, strong cheese)","(ratchet & clank, minecraft)",0.062793,0.257870,0.022019,0.350667,1.359858,1.0,0.005827,1.142911,0.282359,0.073731,0.125041,0.218028
1906,"(ratchet & clank, ratchet & clank 2, minecraft)","(pet food, babies food)",0.075435,0.251256,0.025620,0.339623,1.351700,1.0,0.006666,1.133813,0.281420,0.085095,0.118020,0.220794
1886,"(cooking oil, pokemon sword)","(ratchet & clank, babies food, minecraft)",0.069910,0.223292,0.021015,0.300599,1.346214,1.0,0.005404,1.110533,0.276506,0.077207,0.099531,0.197356
1910,"(pet food, babies food, ratchet & clank 2)","(ratchet & clank, minecraft)",0.074012,0.257870,0.025620,0.346154,1.342358,1.0,0.006534,1.135022,0.275427,0.083652,0.118960,0.222752

 Test set: top 10 rules by lift (support >= 0.05)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
267,"(minecraft, cooking oil)",(burgers),0.173811,0.215673,0.050234,0.289017,1.340071,1.0,0.012748,1.103159,0.307158,0.148075,0.093512,0.260968
270,(burgers),"(minecraft, cooking oil)",0.215673,0.173811,0.050234,0.232919,1.340071,1.0,0.012748,1.077056,0.323553,0.148075,0.071543,0.260968
356,"(ratchet & clank, escalope)","(babies food, minecraft)",0.119223,0.366711,0.057267,0.480337,1.309851,1.0,0.013547,1.218653,0.268574,0.133594,0.179422,0.318251
203,"(babies food, pokemon shield)",(minecraft),0.107167,0.447421,0.062626,0.584375,1.306096,1.0,0.014677,1.329513,0.262489,0.127297,0.247845,0.362173
205,(pokemon shield),"(babies food, minecraft)",0.131614,0.366711,0.062626,0.475827,1.297552,1.0,0.014361,1.208167,0.264074,0.143736,0.172300,0.323302
352,"(ratchet & clank, babies food, escalope)",(minecraft),0.100469,0.447421,0.057267,0.570000,1.273967,1.0,0.012315,1.285067,0.239069,0.116724,0.221830,0.348997
177,(escalope),"(babies food, minecraft)",0.200268,0.366711,0.093436,0.466555,1.272268,1.0,0.019996,1.187168,0.267592,0.197313,0.157659,0.360675
173,"(babies food, minecraft)",(escalope),0.366711,0.200268,0.093436,0.254795,1.272268,1.0,0.019996,1.073170,0.337922,0.197313,0.068181,0.360675
299,"(ratchet & clank, fresh bread)",(minecraft),0.102143,0.447421,0.057937,0.567213,1.267738,1.0,0.012236,1.276792,0.235220,0.117847,0.216787,0.348352
368,"(babies food, minecraft)","(pet food, ratchet & clank)",0.366711,0.183188,0.085064,0.231963,1.266258,1.0,0.017886,1.063506,0.332031,0.182997,0.059714,0.348157

Mean Relative Lift Difference: 0.041935715016955935

# Tech Entusiast

In [11]:
tech_entusiast_df = cluster_groups['Tech Entusiast']
cluster_association_rules(tech_entusiast_df)

We have 11240 rows in the train set.
We have 2811 rows in the test set.

 Frequent Itemsets (support >= 0.5)

      support                             itemsets
12   0.466281                       (energy drink)
24   0.340036                           (pancakes)
38   0.320018                         (white wine)
72   0.269751             (pancakes, energy drink)
29   0.266548                        (protein bar)
..        ...                                  ...
90   0.051068      (samsung galaxy 10, white wine)
103  0.050890  (pancakes, energy bar, protein bar)
75   0.050267             (energy drink, red wine)
37   0.050178                     (vacuum cleaner)
56   0.050089                 (cider, french wine)

[114 rows x 2 columns]

 Association rules (confidence >= 0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(airpods),(energy bar),0.236032,0.178559,0.063701,0.269883,1.511453,1.0,0.021555,1.125082,0.442931,0.181542,0.111176,0.313317
1,(energy bar),(airpods),0.178559,0.236032,0.063701,0.356751,1.511453,1.0,0.021555,1.187671,0.411941,0.181542,0.158016,0.313317
2,(energy drink),(airpods),0.466281,0.236032,0.159875,0.342873,1.452657,1.0,0.049818,1.162589,0.583839,0.294735,0.139851,0.510110
3,(airpods),(energy drink),0.236032,0.466281,0.159875,0.677346,1.452657,1.0,0.049818,1.654154,0.407878,0.294735,0.395462,0.510110
4,(airpods),(gadget for tiktok streaming),0.236032,0.247509,0.078826,0.333962,1.349291,1.0,0.020406,1.129801,0.338849,0.194768,0.114889,0.326219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,"(pancakes, gadget for tiktok streaming)","(energy drink, protein bar)",0.121975,0.209520,0.051868,0.425237,2.029582,1.0,0.026312,1.375316,0.577760,0.185492,0.272894,0.336398
212,"(energy drink, protein bar)","(pancakes, gadget for tiktok streaming)",0.209520,0.121975,0.051868,0.247558,2.029582,1.0,0.026312,1.166901,0.641746,0.185492,0.143029,0.336398
213,"(energy drink, gadget for tiktok streaming)","(pancakes, protein bar)",0.167616,0.155160,0.051868,0.309448,1.994378,1.0,0.025861,1.223427,0.598991,0.191461,0.182624,0.321868
214,"(protein bar, gadget for tiktok streaming)","(pancakes, energy drink)",0.096975,0.269751,0.051868,0.534862,1.982801,1.0,0.025709,1.569964,0.548892,0.164736,0.363043,0.363572
215,(gadget for tiktok streaming),"(pancakes, energy drink, protein bar)",0.247509,0.133096,0.051868,0.209561,1.574513,1.0,0.018926,1.096738,0.484900,0.157781,0.088205,0.299634

 Top 10 rules by lift (support >= 0.02)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
873,"(bramble, dessert wine)","(white wine, cider)",0.043149,0.164769,0.023043,0.534021,3.241032,1.0,0.015933,1.792421,0.722638,0.124639,0.442095,0.336935
872,"(dessert wine, cider)","(bramble, white wine)",0.092260,0.077847,0.023043,0.249759,3.208332,1.0,0.015861,1.229142,0.758269,0.156685,0.186425,0.272879
874,"(bramble, white wine)","(dessert wine, cider)",0.077847,0.092260,0.023043,0.296000,3.208332,1.0,0.015861,1.289404,0.746418,0.156685,0.224448,0.272879
875,"(bramble, cider)","(white wine, dessert wine)",0.057918,0.126157,0.023043,0.397849,3.153616,1.0,0.015736,1.451204,0.724888,0.143094,0.310917,0.290251
881,"(dessert wine, champagne)","(white wine, cider)",0.048043,0.164769,0.024822,0.516667,3.135709,1.0,0.016906,1.728065,0.715466,0.132040,0.421318,0.333657
880,"(dessert wine, cider)","(white wine, champagne)",0.092260,0.087722,0.024822,0.269045,3.067008,1.0,0.016729,1.248063,0.742447,0.159977,0.198758,0.276003
882,"(white wine, champagne)","(dessert wine, cider)",0.087722,0.092260,0.024822,0.282961,3.067008,1.0,0.016729,1.265957,0.738755,0.159977,0.210084,0.276003
405,"(salt, white wine)",(beer),0.037722,0.225356,0.025178,0.667453,2.961773,1.0,0.016677,2.329426,0.688330,0.105834,0.570710,0.389589
883,"(cider, champagne)","(white wine, dessert wine)",0.066459,0.126157,0.024822,0.373494,2.960559,1.0,0.016438,1.394789,0.709370,0.147932,0.283045,0.285125
866,"(beer, cider)","(white wine, dessert wine)",0.094751,0.126157,0.033986,0.358685,2.843177,1.0,0.022032,1.362582,0.716135,0.181818,0.266099,0.314039

 Test set: top 10 rules by lift (support >= 0.05)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
117,"(cider, champagne)",(white wine),0.066524,0.319815,0.056919,0.855615,2.675343,1.0,0.035644,4.710911,0.670844,0.172786,0.787727,0.516795
124,(white wine),"(dessert wine, cider)",0.319815,0.098186,0.081466,0.254727,2.594344,1.0,0.050064,1.210046,0.903498,0.242072,0.173585,0.542219
121,"(dessert wine, cider)",(white wine),0.098186,0.319815,0.081466,0.829710,2.594344,1.0,0.050064,3.994278,0.681455,0.242072,0.749642,0.542219
118,(cider),"(white wine, champagne)",0.242263,0.090715,0.056919,0.234949,2.589963,1.0,0.034942,1.188528,0.810167,0.206186,0.158623,0.431200
116,"(white wine, champagne)",(cider),0.090715,0.242263,0.056919,0.627451,2.589963,1.0,0.034942,2.033927,0.675139,0.206186,0.508340,0.431200
125,(cider),"(white wine, dessert wine)",0.242263,0.130559,0.081466,0.336270,2.575628,1.0,0.049836,1.309933,0.807331,0.279609,0.236602,0.480124
120,"(white wine, dessert wine)",(cider),0.130559,0.242263,0.081466,0.623978,2.575628,1.0,0.049836,2.015142,0.703607,0.279609,0.503757,0.480124
107,(white wine),"(beer, cider)",0.319815,0.105301,0.086446,0.270300,2.566940,1.0,0.052769,1.226120,0.897449,0.255252,0.184419,0.545623
104,"(beer, cider)",(white wine),0.105301,0.319815,0.086446,0.820946,2.566940,1.0,0.052769,3.798769,0.682275,0.255252,0.736757,0.545623
192,"(pancakes, gadget for tiktok streaming)","(energy drink, protein bar)",0.119175,0.196016,0.059409,0.498507,2.543202,1.0,0.036049,1.603183,0.688894,0.232267,0.376241,0.400796

Mean Relative Lift Difference: 0.04636081930630074

# Mature Independent

In [12]:
mature_independent_df = cluster_groups['Mature Independent']
cluster_association_rules(mature_independent_df)

We have 14298 rows in the train set.
We have 3575 rows in the test set.

 Frequent Itemsets (support >= 0.5)

      support                         itemsets
29   0.692824                            (oil)
2    0.470835                 (barbecue sauce)
56   0.394810            (barbecue sauce, oil)
9    0.373759                        (cologne)
79   0.311932                   (cologne, oil)
..        ...                              ...
72   0.050567          (toilet paper, chicken)
12   0.050567                          (cream)
129  0.050287      (chicken, cooking oil, oil)
127  0.050147    (chicken, cologne, deodorant)
53   0.050077  (barbecue sauce, mashed potato)

[148 rows x 2 columns]

 Association rules (confidence >= 0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(antioxydant juice),(barbecue sauce),0.105120,0.470835,0.062526,0.594810,1.263309,1.0,0.013032,1.305969,0.232912,0.121782,0.234285,0.363804
1,(antioxydant juice),(oil),0.105120,0.692824,0.085746,0.815702,1.177358,1.0,0.012917,1.666734,0.168336,0.120397,0.400024,0.469733
2,(black tea),(barbecue sauce),0.111414,0.470835,0.067492,0.605775,1.286598,1.0,0.015034,1.342293,0.250686,0.131114,0.255006,0.374560
3,(cake),(barbecue sauce),0.137502,0.470835,0.072947,0.530519,1.126761,1.0,0.008207,1.127127,0.130436,0.136251,0.112789,0.342725
4,(catfish),(barbecue sauce),0.092740,0.470835,0.051196,0.552036,1.172462,1.0,0.007531,1.181267,0.162130,0.099918,0.153451,0.330385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,"(ham, barbecue sauce)","(cologne, oil)",0.131207,0.311932,0.060288,0.459488,1.473041,1.0,0.019360,1.272994,0.369630,0.157472,0.214450,0.326381
295,"(ham, cologne)","(barbecue sauce, oil)",0.101972,0.394810,0.060288,0.591221,1.497480,1.0,0.020028,1.480480,0.369935,0.138119,0.324544,0.371961
296,"(ham, oil)","(barbecue sauce, cologne)",0.178626,0.228214,0.060288,0.337510,1.478920,1.0,0.019523,1.164978,0.394255,0.173966,0.141614,0.300842
297,"(barbecue sauce, cologne)","(ham, oil)",0.228214,0.178626,0.060288,0.264174,1.478920,1.0,0.019523,1.116261,0.419586,0.173966,0.104152,0.300842
298,(ham),"(barbecue sauce, cologne, oil)",0.216883,0.200867,0.060288,0.277975,1.383873,1.0,0.016723,1.106793,0.354214,0.168656,0.096489,0.289057

 Top 10 rules by lift (support >= 0.02)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
314,"(ratchet & clank, babies food)",(minecraft),0.047909,0.059729,0.022521,0.470073,7.870145,1.0,0.019659,1.774341,0.916863,0.264585,0.436411,0.423561
318,(minecraft),"(ratchet & clank, babies food)",0.059729,0.047909,0.022521,0.377049,7.870145,1.0,0.019659,1.528357,0.928389,0.264585,0.345703,0.423561
316,"(babies food, minecraft)",(ratchet & clank),0.038537,0.074906,0.022521,0.584392,7.801715,1.0,0.019634,2.225882,0.906767,0.247692,0.550740,0.442523
317,(ratchet & clank),"(babies food, minecraft)",0.074906,0.038537,0.022521,0.300654,7.801715,1.0,0.019634,1.374802,0.942415,0.247692,0.272623,0.442523
315,"(ratchet & clank, minecraft)",(babies food),0.026158,0.135753,0.022521,0.860963,6.342114,1.0,0.018970,6.215929,0.864949,0.161565,0.839123,0.513428
254,(minecraft),(ratchet & clank),0.059729,0.074906,0.026158,0.437939,5.846548,1.0,0.021683,1.645897,0.881617,0.241135,0.392429,0.393573
253,(ratchet & clank),(minecraft),0.074906,0.059729,0.026158,0.349206,5.846548,1.0,0.021683,1.444807,0.896080,0.241135,0.307866,0.393573
15,(minecraft),(babies food),0.059729,0.135753,0.038537,0.645199,4.752734,1.0,0.030429,2.435864,0.839752,0.245544,0.589468,0.464537
14,(babies food),(minecraft),0.135753,0.059729,0.038537,0.283874,4.752734,1.0,0.030429,1.312998,0.913622,0.245544,0.238384,0.464537
20,(babies food),(ratchet & clank),0.135753,0.074906,0.047909,0.352911,4.711410,1.0,0.037740,1.429624,0.911487,0.294370,0.300516,0.496250

 Test set: top 10 rules by lift (support >= 0.05)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
4,(ratchet & clank),(babies food),0.077483,0.145175,0.052308,0.675090,4.650188,1.0,0.041059,2.630962,0.850884,0.307061,0.619911,0.517699
5,(babies food),(ratchet & clank),0.145175,0.077483,0.052308,0.360308,4.650188,1.0,0.041059,1.442128,0.918264,0.307061,0.306580,0.517699
179,"(deodorant, chicken)",(cologne),0.088671,0.377622,0.050070,0.564669,1.495327,1.0,0.016586,1.429665,0.363480,0.120296,0.300535,0.348631
249,"(barbecue sauce, deodorant)","(cologne, oil)",0.173427,0.307972,0.078322,0.451613,1.466409,1.0,0.024911,1.261933,0.384796,0.194310,0.207565,0.352964
251,"(cologne, oil)","(barbecue sauce, deodorant)",0.307972,0.173427,0.078322,0.254314,1.466409,1.0,0.024911,1.108474,0.459608,0.194310,0.097859,0.352964
238,"(barbecue sauce, chicken)","(cologne, oil)",0.155804,0.307972,0.070210,0.450628,1.463212,1.0,0.022226,1.259672,0.374998,0.178394,0.206142,0.339301
242,"(cologne, oil)","(barbecue sauce, chicken)",0.307972,0.155804,0.070210,0.227975,1.463212,1.0,0.022226,1.093482,0.457456,0.178394,0.085490,0.339301
241,"(barbecue sauce, cologne)","(oil, chicken)",0.229371,0.210070,0.070210,0.306098,1.457122,1.0,0.022026,1.138388,0.407090,0.190152,0.121565,0.320159
240,"(oil, chicken)","(barbecue sauce, cologne)",0.210070,0.229371,0.070210,0.334221,1.457122,1.0,0.022026,1.157485,0.397144,0.190152,0.136058,0.320159
239,"(cologne, chicken)","(barbecue sauce, oil)",0.123916,0.393007,0.070210,0.566591,1.441683,1.0,0.021510,1.400510,0.349700,0.157170,0.285974,0.372620

Mean Relative Lift Difference: 0.028009567593612283

# Makro Lovers

In [13]:
makro_df = cluster_groups['Makro Lovers']
cluster_association_rules(makro_df)

We have 229 rows in the train set.
We have 58 rows in the test set.

 Frequent Itemsets (support >= 0.5)

      support                        itemsets
20   0.790393                           (oil)
17   0.545852                     (meatballs)
18   0.484716                 (mineral water)
92   0.462882                (meatballs, oil)
100  0.384279            (mineral water, oil)
..        ...                             ...
126  0.052402        (pasta, beer, meatballs)
151  0.052402  (french fries, meatballs, oil)
10   0.052402                      (escalope)
155  0.052402       (ham, mineral water, oil)
42   0.052402             (beer, canned_tuna)

[186 rows x 2 columns]

 Association rules (confidence >= 0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(bacon),(meatballs),0.117904,0.545852,0.069869,0.592593,1.085630,1.0,0.005511,1.114728,0.089418,0.117647,0.102920,0.360296
1,(bacon),(mineral water),0.117904,0.484716,0.056769,0.481481,0.993327,1.0,-0.000381,0.993762,-0.007559,0.104000,-0.006277,0.299299
2,(bacon),(oil),0.117904,0.790393,0.091703,0.777778,0.984039,1.0,-0.001487,0.943231,-0.018056,0.112299,-0.060185,0.446900
3,(bacon),(pasta),0.117904,0.336245,0.056769,0.481481,1.431938,1.0,0.017124,1.280100,0.341965,0.142857,0.218811,0.325156
4,(salmon),(bacon),0.283843,0.117904,0.056769,0.200000,1.696296,1.0,0.023302,1.102620,0.573171,0.164557,0.093069,0.340741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,"(pasta, meatballs)","(salmon, oil)",0.205240,0.240175,0.061135,0.297872,1.240232,1.0,0.011842,1.082175,0.243721,0.159091,0.075935,0.276209
405,"(pasta, oil)","(salmon, meatballs)",0.283843,0.165939,0.061135,0.215385,1.297976,1.0,0.014035,1.063019,0.320557,0.157303,0.059283,0.291903
406,"(salmon, meatballs)","(pasta, oil)",0.165939,0.283843,0.061135,0.368421,1.297976,1.0,0.014035,1.133916,0.275243,0.157303,0.118100,0.291903
407,"(salmon, oil)","(pasta, meatballs)",0.240175,0.205240,0.061135,0.254545,1.240232,1.0,0.011842,1.066141,0.254926,0.159091,0.062038,0.276209
408,(salmon),"(pasta, meatballs, oil)",0.283843,0.183406,0.061135,0.215385,1.174359,1.0,0.009077,1.040757,0.207317,0.150538,0.039161,0.274359

 Top 10 rules by lift (support >= 0.02)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
356,(yogurt cake),(red wine),0.065502,0.039301,0.021834,0.333333,8.481481,1.0,0.019260,1.441048,0.943925,0.263158,0.306061,0.444444
355,(red wine),(yogurt cake),0.039301,0.065502,0.021834,0.555556,8.481481,1.0,0.019260,2.102620,0.918182,0.263158,0.524403,0.444444
2211,"(cider, meatballs)","(oil, eggs)",0.026201,0.131004,0.021834,0.833333,6.361111,1.0,0.018402,5.213974,0.865471,0.161290,0.808208,0.500000
2212,"(cider, oil)","(meatballs, eggs)",0.039301,0.087336,0.021834,0.555556,6.361111,1.0,0.018402,2.053493,0.877273,0.208333,0.513025,0.402778
2210,"(meatballs, eggs)","(cider, oil)",0.087336,0.039301,0.021834,0.250000,6.361111,1.0,0.018402,1.280932,0.923445,0.208333,0.219318,0.402778
2207,"(oil, meatballs, eggs)",(cider),0.078603,0.043668,0.021834,0.277778,6.361111,1.0,0.018402,1.324152,0.914692,0.217391,0.244800,0.388889
2213,(cider),"(oil, meatballs, eggs)",0.043668,0.078603,0.021834,0.500000,6.361111,1.0,0.018402,1.842795,0.881279,0.217391,0.457346,0.388889
2208,"(cider, meatballs, oil)",(eggs),0.021834,0.165939,0.021834,1.000000,6.026316,1.0,0.018211,inf,0.852679,0.131579,1.000000,0.565789
2070,"(salmon, canned_tuna, meatballs)",(whole wheat rice),0.043668,0.087336,0.021834,0.500000,5.725000,1.0,0.018020,1.825328,0.863014,0.200000,0.452153,0.375000
960,(cider),"(meatballs, eggs)",0.043668,0.087336,0.021834,0.500000,5.725000,1.0,0.018020,1.825328,0.863014,0.200000,0.452153,0.375000

 Test set: top 10 rules by lift (support >= 0.05)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
637,"(salmon, mineral water)",(mayonnaise),0.068966,0.051724,0.051724,0.75,14.500000,1.0,0.048157,3.793103,1.000000,0.75,0.736364,0.875
1260,"(salmon, mineral water, meatballs)",(mayonnaise),0.068966,0.051724,0.051724,0.75,14.500000,1.0,0.048157,3.793103,1.000000,0.75,0.736364,0.875
1263,"(salmon, mineral water)","(mayonnaise, meatballs)",0.068966,0.051724,0.051724,0.75,14.500000,1.0,0.048157,3.793103,1.000000,0.75,0.736364,0.875
1266,"(mayonnaise, meatballs)","(salmon, mineral water)",0.051724,0.068966,0.051724,1.00,14.500000,1.0,0.048157,inf,0.981818,0.75,1.000000,0.875
639,(mayonnaise),"(salmon, mineral water)",0.051724,0.068966,0.051724,1.00,14.500000,1.0,0.048157,inf,0.981818,0.75,1.000000,0.875
1267,(mayonnaise),"(salmon, mineral water, meatballs)",0.051724,0.068966,0.051724,1.00,14.500000,1.0,0.048157,inf,0.981818,0.75,1.000000,0.875
844,"(catfish, vegetables mix)","(cake, oil)",0.051724,0.086207,0.051724,1.00,11.600000,1.0,0.047265,inf,0.963636,0.60,1.000000,0.800
843,"(cake, oil)","(catfish, vegetables mix)",0.086207,0.051724,0.051724,0.60,11.600000,1.0,0.047265,2.370690,1.000000,0.60,0.578182,0.800
838,"(cake, catfish, oil)",(vegetables mix),0.051724,0.103448,0.051724,1.00,9.666667,1.0,0.046373,inf,0.945455,0.50,1.000000,0.750
849,(vegetables mix),"(cake, catfish, oil)",0.103448,0.051724,0.051724,0.50,9.666667,1.0,0.046373,1.896552,1.000000,0.50,0.472727,0.750

Mean Relative Lift Difference: 0.4212065776391269